# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "actions-test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Install dependencies
      run: go get -t -v ./...
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -cover ./app ./system
    - name: Govulncheck
      run: /home/runner/go/bin/govulncheck ./...
    - uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: ./app ./system