---

# This file is a workflow configuration file for an integration workflow using
# GitHub Actions.

name: Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/test.yml